### ISSUE TITLE
Catalog rebuild consistently gets stuck

### ISSUE THREAD

**Issue by JonnyGators** [shane-mason/FieldStation42#22] opened 2024-11-10 14:25 UTC
I've still not been able to complete a catalog build with this.  

Previously I had problems building it that I temporarily worked around by reducing the items in a folder.  But I didn't have enough bumpers and commercials for it to build a program.

I've updated things and gave it another try with a commercials path that is mounted to a commercials folder with 245 items.

I notice that this time when running the catalog build, it doesn't list the individual items it is detecting and adding - not sure if that's a change with updates that have been added since I last tried.  But when it got to the commercials path, it has been stuck overnight on the line INFO:test:CAT:Checking for media with in content folder: commercial

What steps should I take to determine why it is getting stuck?

**Comment by JonnyGators** [comment] 2024-11-10 19:37
I have also tried copying the files I am using directly to the folders instead of mounting them to a network path.  The problem persists.  I have been completely unable to complete a catalog build at all.

**Comment by shane-mason** [comment] 2024-11-11 07:03
Yes, there was a recent change to cut down on some of the noise in the output. If it's stuck in that location, there has to be something wrong in the filesystem, like circular links. Are you using any symbolic links in your folders? It now scans for subfolders also, so maybe it's in a loop.

**Comment by shane-mason** [comment] 2024-11-11 07:06
Just to eliminate that its the number of commercials (should not be) - try with 30 or 40 and see if that works.

**Comment by JonnyGators** [comment] 2024-11-11 13:58
Past experience suggests that reducing the number of items to scan may temporarily resolve the issue.  

I think it's not stuck, but it crashes - once it happens, I lose all control or access to the device and have to power it off and back on.

Is there a logging we could enable to begin troubleshooting this issue?

**Comment by shane-mason** [comment] 2024-11-11 16:04
Yes, let's do that. I'll re-enable detailed logging via a command-line switch, and you can pipe that to disk while it's running in case it locks. I have today off and just finished a new video yesterday, so there's no time like right now. Give me a few hours.

**Comment by shane-mason** [comment] 2024-11-11 20:41
Okay - I made the updates to enable debug logging. Do a fresh pull and run `python3 station_42.py --help` you will have two new options and I added short options to the existing ones:

```
  -h, --help            show this help message and exit
  -r, --rebuild_catalog
                        Overwrite catalog if it exists
  -l LOGFILE, --logfile LOGFILE
                        Set logging to use output file - will append each run
  -v, --verbose         Set logging verbosity level to very chatty
```

So, if you run:

`python3 station_42.py -r`

you'll get the normal rebuild options that you were using - `-r` is same as `--rebuild_catalog`

If you run with:

`python3 station_42.py -r -v`

You'll get the new debug verbose mode. This is mainly for the catalog building step so far, I haven't added a lot of debug to the scheduler yet. Later today maybe.

If you run with something like:

`python3 station_42.py  -r -v -l mytest.log`

It will now append log messages (with a timestamp) to the file 'mytest.log' - in case the font isn't clear, that's a lower case L - as in Log.

Give it a try and see if it works for you.

**Comment by JonnyGators** [comment] 2024-11-11 21:58
Ok, I've created the log.  It appears to just plain stop at some point, and which point the whole pi becomes stuck.

No other process has ever locked up or frozen my pi, I'm not sure why this one is.

[mytest.log](https://github.com/user-attachments/files/17708514/mytest.log)

**Comment by shane-mason** [comment] 2024-11-11 22:32
Dude - corner gas is one of the best shows of all time - its a shame that it got stuck there...

The next thing that happens in that code block is a call to FFMPEG to get metadata on the movie file - duration mainly.

- If you run it again and it gets stuck in the same place
  - Then this file is causing FFMEG some problems - try to play it and make sure it works
- If you run it again and it gets stuck in a different place
  -  Then its not file specific, but could be a different problem in my python but feels more like its problem with the hardware since this just isn't enough files to cause a memory issue

I suspect a harddrive problem, mainly because that's what is at work here - not a lot in the memory area really. What kind of hard disk are you using?  If other programs don't cause this problem, it could be that they aren't hitting the error condition. I would run a disk test:

```
$ sudo apt-get install smartmontools
```
and then run:

```
$ sudo smartctl -t long -d sat /dev/sda -T permissive
```

It will take a long time, but if this works then your disk should be fine.

**Comment by JonnyGators** [comment] 2024-11-12 00:26
I was mounting paths to folders on my media server when I started, but to remove the possibility of network/wifi type issues, I copied this content directly to the microSD card I have in the pi.  Being that I'm seeing the same thing with the data stored in 2 different locations, I don't think it's a drive issue.  

The process does seem to get stuck at the same point, but I'm not sure that it's a same file issue.

Since this folder just consists of copies of files from my media server, I'm just deleting the file it gets stuck on.

First time I did this, it went through in the same order as before, and got stuck at the next file after the one I deleted.  So I deleted that one.

Now it got stuck 2 past that one.

I can keep going - but it doesn't seem file based, it seems time or number of files processed based.  

It could be hardware - but doing things like leaving it on hours at a time playing videos or TV tuner feed hasn't ever crashed or overloaded it.  I'm not sure what the next steps would be to determine what is going on hardware related that could be crashing things.

**Comment by shane-mason** [comment] 2024-11-12 01:35
Okay - this is good information that it gets stuck at the same point.  And if you try to play the file it gets stuck on with mpv, it plays fine?

I don't see how it could be the number of files processed though - there just aren't that many titles in the logfile before it stops - just about 100? It gets through my collection fine which has many hundreds.  A python program running in user space shouldn't be able to cause a kernel panic and have the machine lock up. It could run it out of memory - that's possible. Have you watched top or monitored your system resources while this is running? Also, how long does it take to get this far, before it hangs?

Also, `/var/log/dmesg` holds the kernel messages and is a good place to start looking if the system is getting locked up.

**Comment by shane-mason** [comment] 2024-11-13 07:58
Okay - after some profile testing, I do not think that this has anything to do with the number of files being processed. Here's what I did: 

I created 1 station with a set of folders with ascending counts of videos in them: 10, 15, 20, 25, 70, 100, 120, 200 + 100 commercials and 100 bumps == 870 videos. Each video file is unique and varies from 30 minutes to 2 hours in duration (besides the commercials and bumps). The main idea here is to test various sizes of folders. I ran the catalog build multiple times and monitored its memory usage, here is what I observed that the max memory usage over lots of runs and it tops out at around 400mb.

I then added additional content from my library to the same station until its at 1958 videos and it tops out around 450mb resident memory.  In this case, we added 1088 videos at the cost of 50mb of memory - or 125% more videos for 12.5% more memory. This profile meets my expectation - memory is not growing out of bounds - as new videos are added the memory usage is growing linearly.

It does spin up a lot of FFMPEG processes, but they close out pretty quickly. The system memory rises and falls as the catalog is being built - the overall used memory doesn't continue growing as new videos are being added. 

These aren't huge numbers of files, but they are much more than where yours is failing - so I don't think its a problem in the python code. Have you tried playing the specific files that are failing and confirmed that they play in MPV and are valid files?

**Comment by shane-mason** [comment] 2024-11-24 18:10
Closing this issue since stress testing showed the performance to be in-bounds and no follow-up from OP on whether attempting to play the failing videos showed they were valid. Additionally - I just ran a catalog build for my entire catalog over a network mount and it worked fine. My best current guess is that you have some bad video files - until you test them and confirm they work, I can't do more.

**Comment by shane-mason** [comment] 2024-11-24 18:11
Problem appears to be with users files.

**Closed by shane-mason** 2024-11-24 18:11 UTC

**Comment by JonnyGators** [comment] 2024-11-24 18:26
I'm still consistently having these problems.  I have never been able to get this project to work.  It's quite a disappointment.

**Comment by JonnyGators** [comment] 2024-11-24 18:28
It is quite disappointing to report a problem that renders this project completely unusable, and to just have the problem dismissed like this.

**Comment by shane-mason** [comment] 2024-11-24 20:09
Its weird that you feel so entitled to my time and efforts.  I did a lot of work to try and help you - its all documented in the threads above.

You are disappointed, but maybe take a few minutes to think about what you are actually entitled to here. This is a free project that I do on my precious little bit of spare time. This project is usable - there are literally hundreds of people using it now - you clearly have something going on in your hardware or network - your setup is the odd-man-out.

Since you have been rude since our first interaction on youtube, you are free to build your own, look for other projects or go down to wal-mart and pick up a product you might stand a chance of figuring out - but I will not be welcoming anymore questions or input from you.

**Comment by JonnyGators** [comment] 2024-11-24 20:12
I've tried to help you improve this project and have invested a lot of time into trying to build this and follow your instructions.

I have appreciated your time and efforts, and have thanked you every step of the way.

I've simply reached out asking for help, given that this project hasn't worked when following all of your instructions to the letter.  I had hoped my efforts would be of help to you, this looks like a really cool project and I've said as much many times.  But when I invest many hours of time into troubleshooting and, basically doing QA work for you for free, and you just dismiss it as if there isn't a problem, that is frustrating.

**Comment by shane-mason** [comment] 2024-11-24 20:55
>  basically doing QA work for you for free and you just dismiss it as if there isn't a problem, that is frustrating.

This is laughable! I'm debugging your raspberry pi and network issues here - you haven't provided any useful input on the actual project at all. Its only frustrating to you because you feel entitled to have stuff just work, and if it doesn't someone else needs to figure it out for you for free. The thread above shows I didn't dismiss you. Try it on different hardware (boot a linux VM or use WSL if you don't have a Linux box) - but don't expect that I can magically fix your issues when no-one else seems to be able to reproduce them. 

Actually - now that I look at your 'contributions' to other projects on github, I find an interesting trend: you begging people to help you figure stuff out that works for everyone else and then your abusive towards them:

[This one](https://github.com/LibreELEC/LibreELEC.tv/issues/9181#issuecomment-2287771141) is because you couldn't figure out  how to configure your audio output:
>I've yet to encounter a more stupid scenario than an audio player that is designed to not output audio.

[This one](https://github.com/tp7/Average/issues/1#issue-2404512280), you just started off mean and weird:

>Also, I'd recommend using proper english in the error messages. Encountering errors with such poor use of english does not give me much faith in the quality of the product.

Though I do find it telling that your own English is so good but you don't know the word 'english' should be capitalized? Check yourself before you throw stones at others.

After looking through your 'contributions', I don't feel bad at all telling you to either build your own, figure it out yourself or pound sand - I literally couldn't care less which you choose.

**Comment by JonnyGators** [comment] 2024-11-24 21:04
My apologies for my poor English.  However, I do stand behind my opinion that an audio player that disables the audio output by default is a poor choice of design.  Not that that has any relevance to the crashing that occurs when trying to build a catalog.
